services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: itp-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run start
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: itp-backend-dev
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped
